language: lisp
sudo: required

# https://gist.github.com/fukamachi/52dce85caf477043ffeb

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - mkdir -p ~/.roswell/lisp/quicklisp/dists/pauldist
  - curl -L http://pauldist.kisp.in/pauldist.txt > ~/.roswell/lisp/quicklisp/dists/pauldist/distinfo.txt
  - touch  ~/.roswell/lisp/quicklisp/dists/pauldist/enabled.txt
  - cd ~/lisp && git clone https://github.com/kisp/argsem-soundness.git
  - cd ~/lisp && git clone https://github.com/kisp/graph-adj.git
  - cd ~/lisp && git clone https://github.com/kisp/graph-tgf.git
  - cd ~/lisp && git clone https://github.com/kisp/graph-apx.git
  - cd ~/lisp && git clone https://github.com/kisp/trivial-graph-canonization.git

script:
  - ros -e '(format t "~A ~A~%" (lisp-implementation-type) (lisp-implementation-version))'
  - ros -s arfe-test -e '(uiop:quit (if (myam:load-and-run! "arfe-test") 0 1))'
